name: number_searcher_clean_architecture
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: 8.0.0
  equatable: 2.0.5
  dartz: 0.10.1
  connectivity: 3.0.6
  dio: 5.7.0
  flutter_bloc: ^8.1.6
  http: 1.2.2
  internet_connection_checker: ^1.0.0
  shared_preferences: 2.3.2

  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: 5.4.4
  build_runner:
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
